objects/DNV_Custom_Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Attachment__c</fullName>
        <label>Attachment</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>DNV_Custom_Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Created_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User that created the original Attachment before conversion to Contract</description>
        <label>Original Created By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Created_Date__c</fullName>
        <description>Created Date of an original Attachment before conversion to Contract</description>
        <label>Original Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Original_Last_Modified_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User that made a last change on the original Attachment before conversion to Contract</description>
        <label>Original Last Modified By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Last_Modified_Date__c</fullName>
        <description>Last Modified Date of the original Attachment before conversion to Contract</description>
        <label>Original Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contract</fullName>
                    <default>true</default>
                    <label>Contract</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DNV_CustomAttachmentService.cls
/**
 * Created by Martin Satke on 16-Apr-18.
 */

public with sharing class DNV_CustomAttachmentService {

    public static final String CUSTOM_ATTACHMENT_TYPE_CONTRACT = 'Contract';

    public DNV_CustomAttachmentService() {}

    public DNV_Custom_Attachment__c createCustomAttachment(SObject parentObject, String attachmentType, String description) {
        DNV_Custom_Attachment__c customAttachment = new DNV_Custom_Attachment__c();
        customAttachment.description__c = description;
        customAttachment.type__c = attachmentType;
        customAttachment = updateParentReference(parentObject, customAttachment);
        insert customAttachment;
        return customAttachment;
    }

    private DNV_Custom_Attachment__c updateParentReference(sObject parentObject, DNV_Custom_Attachment__c customAttachment) {
        if (parentObject != null) {
            if (parentObject instanceof Schema.Opportunity) {
                customAttachment.Opportunity__c = parentObject.Id;
            }
        }
        return customAttachment;
    }

    public DNV_Custom_Attachment__c attachFileToCustomAttachment(DNV_Custom_Attachment__c customAttachment, ContentDocument fileToAttach) {
        customAttachment.name = fileToAttach.Title;
        customAttachment.Attachment__c = fileToAttach.id;
        customAttachment = populateOriginalDataOfCreatedContract(customAttachment);
        update customAttachment;
        return customAttachment;
    }

    private DNV_Custom_Attachment__c populateOriginalDataOfCreatedContract(DNV_Custom_Attachment__c customAttachment) {
        customAttachment.Original_Created_Date__c = customAttachment.CreatedDate;
        customAttachment.Original_Created_By__c = customAttachment.CreatedById;
        customAttachment.Original_Last_Modified_Date__c = customAttachment.LastModifiedDate;
        customAttachment.Original_Last_Modified_By__c = customAttachment.LastModifiedById;
        return customAttachment;
    }

    public DNV_Custom_Attachment__c populateCustomAttachmentByOriginalAttachmentData(DNV_Custom_Attachment__c customAttachment, CombinedAttachment originalAttachment) {
        customAttachment.Original_Created_Date__c = originalAttachment.CreatedDate;
        customAttachment.Original_Created_By__c = originalAttachment.CreatedById;
        customAttachment.Original_Last_Modified_Date__c = originalAttachment.LastModifiedDate;
        customAttachment.Original_Last_Modified_By__c = originalAttachment.LastModifiedById;
        return customAttachment;
    }
}